// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dataaccess

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
