// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/users/users.proto

package users_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginUserRequestDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequestDto) Reset() {
	*x = LoginUserRequestDto{}
	mi := &file_proto_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequestDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequestDto) ProtoMessage() {}

func (x *LoginUserRequestDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequestDto.ProtoReflect.Descriptor instead.
func (*LoginUserRequestDto) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *LoginUserRequestDto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequestDto) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResult) Reset() {
	*x = LoginUserResult{}
	mi := &file_proto_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResult) ProtoMessage() {}

func (x *LoginUserResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResult.ProtoReflect.Descriptor instead.
func (*LoginUserResult) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *LoginUserResult) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginUserResult) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginUserResponseDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*LoginUserResult     `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponseDto) Reset() {
	*x = LoginUserResponseDto{}
	mi := &file_proto_users_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponseDto) ProtoMessage() {}

func (x *LoginUserResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponseDto.ProtoReflect.Descriptor instead.
func (*LoginUserResponseDto) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUserResponseDto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginUserResponseDto) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginUserResponseDto) GetData() []*LoginUserResult {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterUserRequestDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequestDto) Reset() {
	*x = RegisterUserRequestDto{}
	mi := &file_proto_users_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequestDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequestDto) ProtoMessage() {}

func (x *RegisterUserRequestDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequestDto.ProtoReflect.Descriptor instead.
func (*RegisterUserRequestDto) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterUserRequestDto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequestDto) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterUserResponseDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponseDto) Reset() {
	*x = RegisterUserResponseDto{}
	mi := &file_proto_users_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponseDto) ProtoMessage() {}

func (x *RegisterUserResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponseDto.ProtoReflect.Descriptor instead.
func (*RegisterUserResponseDto) Descriptor() ([]byte, []int) {
	return file_proto_users_users_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterUserResponseDto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterUserResponseDto) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_users_users_proto protoreflect.FileDescriptor

const file_proto_users_users_proto_rawDesc = "" +
	"\n" +
	"\x17proto/users/users.proto\x12\x05users\"G\n" +
	"\x13LoginUserRequestDto\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Y\n" +
	"\x0fLoginUserResult\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"t\n" +
	"\x14LoginUserResponseDto\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x03(\v2\x16.users.LoginUserResultR\x04data\"J\n" +
	"\x16RegisterUserRequestDto\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"K\n" +
	"\x17RegisterUserResponseDto\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa0\x01\n" +
	"\x05Users\x12F\n" +
	"\tLoginUser\x12\x1a.users.LoginUserRequestDto\x1a\x1b.users.LoginUserResponseDto\"\x00\x12O\n" +
	"\fRegisterUser\x12\x1d.users.RegisterUserRequestDto\x1a\x1e.users.RegisterUserResponseDto\"\x00B\x1cZ\x1aproto/products/users_protob\x06proto3"

var (
	file_proto_users_users_proto_rawDescOnce sync.Once
	file_proto_users_users_proto_rawDescData []byte
)

func file_proto_users_users_proto_rawDescGZIP() []byte {
	file_proto_users_users_proto_rawDescOnce.Do(func() {
		file_proto_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_users_users_proto_rawDesc), len(file_proto_users_users_proto_rawDesc)))
	})
	return file_proto_users_users_proto_rawDescData
}

var file_proto_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_users_users_proto_goTypes = []any{
	(*LoginUserRequestDto)(nil),     // 0: users.LoginUserRequestDto
	(*LoginUserResult)(nil),         // 1: users.LoginUserResult
	(*LoginUserResponseDto)(nil),    // 2: users.LoginUserResponseDto
	(*RegisterUserRequestDto)(nil),  // 3: users.RegisterUserRequestDto
	(*RegisterUserResponseDto)(nil), // 4: users.RegisterUserResponseDto
}
var file_proto_users_users_proto_depIdxs = []int32{
	1, // 0: users.LoginUserResponseDto.data:type_name -> users.LoginUserResult
	0, // 1: users.Users.LoginUser:input_type -> users.LoginUserRequestDto
	3, // 2: users.Users.RegisterUser:input_type -> users.RegisterUserRequestDto
	2, // 3: users.Users.LoginUser:output_type -> users.LoginUserResponseDto
	4, // 4: users.Users.RegisterUser:output_type -> users.RegisterUserResponseDto
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_users_users_proto_init() }
func file_proto_users_users_proto_init() {
	if File_proto_users_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_users_users_proto_rawDesc), len(file_proto_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_users_users_proto_goTypes,
		DependencyIndexes: file_proto_users_users_proto_depIdxs,
		MessageInfos:      file_proto_users_users_proto_msgTypes,
	}.Build()
	File_proto_users_users_proto = out.File
	file_proto_users_users_proto_goTypes = nil
	file_proto_users_users_proto_depIdxs = nil
}
