// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dataaccess

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID            int32            `json:"id"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	Price         pgtype.Numeric   `json:"price"`
	Category      pgtype.Text      `json:"category"`
	StockQuantity pgtype.Int4      `json:"stock_quantity"`
	Sku           pgtype.Text      `json:"sku"`
	IsActive      pgtype.Bool      `json:"is_active"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
}
