// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package dataaccess

import (
	"context"
)

const allProducts = `-- name: AllProducts :many
SELECT id, name, description, price, category, stock_quantity, sku, is_active, created_at, updated_at, deleted_at FROM products WHERE is_active = true AND deleted_at IS NULL
`

func (q *Queries) AllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, allProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.StockQuantity,
			&i.Sku,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
