// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dataaccess

import (
	"context"
)

type Querier interface {
	AllProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
